var baseSeasonsList = [
    "Legendary",
    "Mythic",
    "Rearmed",
    "Ascendant",
    "New Year's",
    "Plegian",
    "Hatari",
    "Khadein",
    "Hot Springs",
    "Valentine's",
    "Spring",
    "Easter",
    "Child",
    "Picnic",
    "Wedding",
    "Fallen",
    "Summer",
    "Brave",
    "Talk Like a Pirate Day",
    "Ninja",
    "Phantom Thief",
    "Ballroom",
    "Day of the Twelve",
    "Yukata",
    "Halloween",
    "Christmas",
];

var otherSeasonsList = [
    "Lunar New Year",
    "St. Patrick's Day",
    "White Day",
    "Mardi Gras",
    "April Fool's",
    "420",
    "Arbor Day",
    "Cinco de Mayo",
    "Mother's Day",
    "Eid al-Fitr",
    "Father's Day",
    "American Independence",
    "Pi Approximation Day",
    "Labour Day",
    "Back to School",
    "Leif Erikson Day",
    "Harvest Moon Festival",
    "Canadian Thanksgiving",
    "Guy Fawkes Day",
    "Black Friday",
    "Hanukkah",
    "Boxing Day",
    "Kwanzaa",
    "OSHA compliant",
    "Doctor",
    "Pride Month",
    "Super Bowl",
    "Chef",
    "Idol",
    "Magical Girl",
    "Attorney",
    "Heroic Spirit",
    "Trucker",
    "Grand",
    "Bondforged",
]; 
