var seasons = [
    "New Year's",
    "Hot Springs",
    "Valentine's",
    "Spring",
    "Easter",
    "Picnic",
    "Wedding",
    "Fallen",
    "Summer",
    "Brave",
    "Talk Like a Pirate Day",
    "Ninja",
    "Ballroom",
    "Yukata",
    "Halloween",
    "Christmas",
    "Groundhog Day",
    "Lunar New Year",
    "St. Patrick's Day",
    "White Day",
    "Mardi Gras",
    "April Fool's",
    "420",
    "Arbor Day",
    "Cinco de Mayo",
    "Mother's Day",
    "Eid al-Fitr",
    "Dragon Boat",
    "Father's Day",
    "American Independence",
    "Pi Approximation Day",
    "Labour Day",
    "Back to School",
    "Leif Erikson Day",
    "Harvest Moon Festival",
    "Canadian Thanksgiving",
    "Guy Fawkes Day",
    "Black Friday",
    "Hanukkah",
    "Boxing Day",
    "Kwanzaa",
    "OSHA compliant",
    "Social Distancing",
    "Doctor",
    "Pride Month",
    "Super Bowl",
    "Chef",
    "Idol",
    "Attorney",
    "Heroic Spirit",
    "Trucker",
    "Plegian",
]
